### ISSUE TITLE
Create abstract GameComponent structure

### ISSUE THREAD

**Issue by FelipeCoimbra** [FelipeCoimbra/fruits-pygame#3]
Classes like Mesh, RigidBody and Collider represent possible GameComponents. GameComponents are attached to GameObjects to add them some specific ability, such as collision capability or graphical style.

It should be useful to wrap them in some standardized abstract class and make every GameObject possess some kind of GameComponents container.

**Comment by igorbragaia** [comment]
Solution: GameObject inherits now from GameComponents, which inherits from all components like Mesh, RigidBody, Collider. In GameComponents there is a method set_component which expects a component name and those parameters required to set this component up through __init__ method.

**Comment by luisholanda** [comment]
I don't think that is a good solution, not all `GameObject`s are collidable or rigid, so don't make sense inheriting from `RigidBody` or `Collider` if it's not rigid or collidable.

A better solution would be making `Mesh`, `RigidBody` and `Collider` cases of the same abstract class and them making `GameObject` hold it components through a `components` property.
What you guys think?

**Comment by FelipeCoimbra** [comment]
Yea the solution I first thought

**Comment by igorbragaia** [comment]
fixed
